<h1>Guzzle</h1>
<div class="tracy-inner">
	<table style="width: 100%;">
		<tr>
			<th>Request</th>
			<th>Reponse</th>
			<th>Time</th>
		</tr>
		<?php foreach ($snapshots as $counter => $snapshot) {
			?>
			<?php $response = $snapshot->getResponse(); ?>
			<?php $request = $snapshot->getRequest(); ?>

			<tr>
				<td>
					<?= htmlspecialchars($request->getMethod(), ENT_QUOTES); ?>
					<?= htmlspecialchars($request->getUri(), ENT_QUOTES); ?>
					<br>

					<strong>Headers:</strong>
					<?= \Tracy\Dumper::toHtml($request->getHeaders(), [
						\Tracy\Dumper::COLLAPSE_COUNT => 1,
						\Tracy\Dumper::COLLAPSE => 1,
					]); ?>
					<br>

					<strong>Body:</strong>
					<?php if (isset($request->getHeader('Content-Type')[0]) && strpos($request->getHeader('Content-Type')[0], 'application/json') !== false) {
						?>
						<?= \Tracy\Dumper::toHtml(json_decode($request->getBody(), true), [Tracy\Dumper::COLLAPSE_COUNT => 1, Tracy\Dumper::COLLAPSE => 1]); ?>
					<?php } else {
						?>
						<?= \Tracy\Dumper::toHtml((string) $request->getBody(), [Tracy\Dumper::COLLAPSE_COUNT => 1, Tracy\Dumper::COLLAPSE => 1]); ?>
						<?php

					} ?>
				</td>
				<td>
					<?= htmlspecialchars($response->getStatusCode(), ENT_QUOTES); ?>
					<?= htmlspecialchars($response->getReasonPhrase(), ENT_QUOTES); ?>
					<br>

					<strong>Headers:</strong>
					<?= \Tracy\Dumper::toHtml($response->getHeaders(), [
						\Tracy\Dumper::COLLAPSE_COUNT => 1,
						\Tracy\Dumper::COLLAPSE => 1,
					]); ?>
					<br>

					<strong>Body:</strong>
					<?php if ($response->getHeader('Content-Type') && strpos($response->getHeader('Content-Type')[0], 'application/json') !== false) {
						?>
						<?= \Tracy\Dumper::toHtml(json_decode($response->getBody(), true), [
							\Tracy\Dumper::COLLAPSE_COUNT => 1,
							\Tracy\Dumper::COLLAPSE => 1,
						]); ?>
					<?php } else {
						?>
						<?= \Tracy\Dumper::toHtml((string) $response->getBody(), [
							\Tracy\Dumper::COLLAPSE_COUNT => 1,
							\Tracy\Dumper::COLLAPSE => 1,
						]); ?>
						<?php

					} ?>
				</td>
				<td><?= ($snapshot->getTime() ? sprintf('%0.1f ms', $snapshot->getTime() * 1000) : ''); ?></td>
			</tr>
			<?php

		} ?>
	</table>
</div>
